export const videoConstants = {
  GET_VIDEOS: "GET_VIDEOS",
  LOADING: "LOADING",
  ERROR: "ERROR",
  FILTER_CATEGORY: "FILTER_CATEGORY",
  SEARCH: "SEARCH",
};

export const likedConstants = {
  ADD_TO_LIKED: "ADD_TO_LIKED",
  REMOVE_FROM_LIKED: "REMOVE_FROM_LIKED",
  ERROR: "ERROR",
};
export const watchLaterConstants = {
  ADD_TO_WATCH_LATER: "ADD_TO_WATCH_LATER",
  REMOVE_FROM_WATCH_LATER: "REMOVE_FROM_WATCH_LATER",
};

export const playlistConstants = {
  GET_PLAYLISTS: "GET_PLAYLISTS",
  ADD_PLAYLIST: "ADD_PLAYLIST",
  DELETE_PLAYLIST: "DELETE_PLAYLIST",
  GET_PLAYLIST_BY_ID: "GET_PLAYLIST_BY_ID",
  ADD_VIDEO_TO_PLAYLIST: "ADD_VIDEO_TO_PLAYLIST",
  DELETE_VIDEO_FROM_PLAYLIST: "DELETE_VIDEO_FROM_PLAYLIST",
};
